---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a-really-really-really-really-really-really-long-name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/glasser/argo-local-dev-test.git'
    path: bar
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bar
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: another-really-really-really-really-really-really-long-name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/glasser/argo-local-dev-test.git'
    path: bar
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: barf
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a-third-really-really-really-really-really-really-long-name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/glasser/argo-local-dev-test.git'
    path: bar
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bark
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a-fourth-really-really-really-really-really-really-long-name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/glasser/argo-local-dev-test.git'
    path: bar4
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bark
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
